### ISSUE TITLE
[project uses unlicense, license] Do you have intentions to license this repo?

### ISSUE THREAD

**Issue by jrschumacher** [muhlemmer/gu#4] opened 2024-10-11 21:44 UTC
The project https://github.com/zitadel/oidc is using this (under an Apache license).

**Comment by muhlemmer** [comment] 2024-10-15 10:58
The project is released into the public domain and uses the [unlicense](https://unlicense.org/) to have a legal fallback copyright notice for jurisdictions that don't allow public domain: https://github.com/muhlemmer/gu/blob/main/LICENSE

As unlicense / public domain is way more permissive as Apache, there should not be any conflict there.

I'm not sure what the issue is here?

**Comment by jrschumacher** [comment] 2024-10-15 14:03
Thank you. Our license checking systems are unfamiliar with this and it was interpreted as "unlicensed" as in no license specified. Thanks for the clarification.

**Closed as completed** 2024-10-15 14:04 UTC
